package com.mathtutor.report;

import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.mathtutor.common.AiException;
import com.mathtutor.report.dto.ReportDto;
import com.mathtutor.report.dto.ReportDto.TopicLine;
import org.springframework.stereotype.Component;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.util.List;

/** Renders a {@link ReportDto} into a printable PDF using OpenPDF. */
@Component
public class ReportPdfRenderer {

    private static final Color INDIGO = new Color(0x4F, 0x46, 0xE5);
    private static final Color GREEN = new Color(0x16, 0xA3, 0x4A);
    private static final Color AMBER = new Color(0xB4, 0x53, 0x09);
    private static final Color GREY = new Color(0x6B, 0x72, 0x80);
    private static final Color HEADER_BG = new Color(0xEE, 0xF2, 0xFF);

    public byte[] render(ReportDto r) {
        Document doc = new Document(PageSize.A4, 42, 42, 42, 42);
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            PdfWriter.getInstance(doc, out);
            doc.open();

            doc.add(title("Aria — Progress Report"));
            doc.add(subtitle(r.studentName() + (r.gradeName().isBlank() ? "" : "  ·  " + r.gradeName())));
            doc.add(muted(capitalize(r.scope()) + " report  ·  " + r.periodStart() + " – " + r.periodEnd()
                    + "  ·  Generated " + r.generatedAt()));
            doc.add(gap(10));

            doc.add(heading("At a glance"));
            doc.add(statsTable(new String[][]{
                    {"Level", String.valueOf(r.level())},
                    {"Total XP", String.valueOf(r.xpTotal())},
                    {"Streak", r.streak() + " days"},
                    {"Accuracy", r.accuracy() + "%"},
                    {"Mastered", String.valueOf(r.masteredCount())},
                    {"In progress", String.valueOf(r.inProgressCount())},
            }));
            doc.add(gap(8));

            doc.add(heading("This period"));
            doc.add(statsTable(new String[][]{
                    {"XP earned", String.valueOf(r.periodXp())},
                    {"Activities", String.valueOf(r.periodActivities())},
                    {"Active days", String.valueOf(r.activeDays())},
            }));
            doc.add(gap(8));

            doc.add(heading("Mastery by topic"));
            doc.add(masteryTable(r.masteryByTopic()));
            doc.add(gap(8));

            doc.add(heading("Strengths"));
            doc.add(bulletList(r.strengths(), "Nothing flagged yet.", GREEN));
            doc.add(heading("Needs work"));
            doc.add(bulletList(r.weaknesses(), "Nothing flagged — great!", AMBER));
            doc.add(heading("Recommendations"));
            doc.add(bulletList(r.recommendations(), "Keep up the good work!", INDIGO));

            if (r.advice() != null && !r.advice().isBlank()) {
                doc.add(gap(6));
                doc.add(heading("A note from Aria"));
                doc.add(body(r.advice()));
            }

            doc.add(gap(14));
            doc.add(muted("Generated by Aria — your child's AI math tutor."));

            doc.close();
            return out.toByteArray();
        } catch (Exception e) {
            throw new AiException("Failed to render report PDF", e);
        }
    }

    // ----- building blocks -------------------------------------------------

    private Paragraph title(String text) {
        return new Paragraph(text, FontFactory.getFont(FontFactory.HELVETICA, 22, Font.BOLD, INDIGO));
    }

    private Paragraph subtitle(String text) {
        Paragraph p = new Paragraph(text, FontFactory.getFont(FontFactory.HELVETICA, 14, Font.BOLD));
        p.setSpacingBefore(2);
        return p;
    }

    private Paragraph muted(String text) {
        return new Paragraph(text, FontFactory.getFont(FontFactory.HELVETICA, 9, Font.NORMAL, GREY));
    }

    private Paragraph heading(String text) {
        Paragraph p = new Paragraph(text, FontFactory.getFont(FontFactory.HELVETICA, 13, Font.BOLD, INDIGO));
        p.setSpacingBefore(10);
        p.setSpacingAfter(4);
        return p;
    }

    private Paragraph body(String text) {
        return new Paragraph(text, FontFactory.getFont(FontFactory.HELVETICA, 11, Font.NORMAL));
    }

    private Paragraph gap(float h) {
        Paragraph p = new Paragraph(" ");
        p.setLeading(h);
        return p;
    }

    private PdfPTable statsTable(String[][] pairs) {
        PdfPTable table = new PdfPTable(pairs.length);
        table.setWidthPercentage(100);
        Font label = FontFactory.getFont(FontFactory.HELVETICA, 8, Font.NORMAL, GREY);
        Font value = FontFactory.getFont(FontFactory.HELVETICA, 15, Font.BOLD, INDIGO);
        for (String[] pair : pairs) {
            PdfPCell cell = new PdfPCell();
            cell.setBorder(0);
            cell.setPadding(6);
            cell.addElement(new Phrase(pair[1], value));
            cell.addElement(new Phrase(pair[0], label));
            table.addCell(cell);
        }
        return table;
    }

    private PdfPTable masteryTable(List<TopicLine> lines) {
        PdfPTable table = new PdfPTable(new float[]{4, 2, 2, 2, 2});
        table.setWidthPercentage(100);
        headerCell(table, "Topic");
        headerCell(table, "Status");
        headerCell(table, "Mastery");
        headerCell(table, "Quiz");
        headerCell(table, "Homework");
        for (TopicLine t : lines) {
            cell(table, t.topicName(), Element.ALIGN_LEFT);
            cell(table, prettyStatus(t.status()), Element.ALIGN_CENTER);
            cell(table, t.total() + "%", Element.ALIGN_CENTER);
            cell(table, t.quiz() == null ? "—" : t.quiz() + "%", Element.ALIGN_CENTER);
            cell(table, t.homework() == null ? "—" : t.homework() + "%", Element.ALIGN_CENTER);
        }
        return table;
    }

    private void headerCell(PdfPTable table, String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, FontFactory.getFont(FontFactory.HELVETICA, 9, Font.BOLD)));
        cell.setBackgroundColor(HEADER_BG);
        cell.setPadding(5);
        table.addCell(cell);
    }

    private void cell(PdfPTable table, String text, int align) {
        PdfPCell cell = new PdfPCell(new Phrase(text, FontFactory.getFont(FontFactory.HELVETICA, 10, Font.NORMAL)));
        cell.setPadding(5);
        cell.setHorizontalAlignment(align);
        table.addCell(cell);
    }

    private Paragraph bulletList(List<String> items, String empty, Color color) {
        if (items == null || items.isEmpty()) {
            return muted(empty);
        }
        Paragraph p = new Paragraph();
        Font f = FontFactory.getFont(FontFactory.HELVETICA, 11, Font.NORMAL, color);
        for (String item : items) {
            Paragraph line = new Paragraph("•  " + item, f);
            line.setLeading(15);
            p.add(line);
        }
        return p;
    }

    private String prettyStatus(String status) {
        return switch (status) {
            case "MASTERED" -> "Mastered";
            case "IN_PROGRESS" -> "In progress";
            case "AVAILABLE" -> "Ready";
            case "LOCKED" -> "Locked";
            default -> status;
        };
    }

    private String capitalize(String s) {
        if (s == null || s.isEmpty()) {
            return s;
        }
        return s.charAt(0) + s.substring(1).toLowerCase();
    }
}
