import type { Skill } from '@aria/shared';

/** The intentionally small arithmetic slice that P0-16 must solve deterministically. */
export const ARITHMETIC_SKILLS = [
  {
    id: 'skill-num-cnt-20',
    subject: 'arithmetic',
    strand: 'number-sense',
    code: 'NUM.CNT.20',
    name: 'Count to 20',
    band: 'early',
    prerequisites: [],
    lessonRef: 'lesson-num-cnt-20',
    visualKinds: ['number-line', 'ten-frame'],
  },
  {
    id: 'skill-num-cnt-skip5',
    subject: 'arithmetic',
    strand: 'number-sense',
    code: 'NUM.CNT.SKIP5',
    name: 'Skip count by 5',
    band: 'early',
    prerequisites: ['NUM.CNT.20'],
    lessonRef: 'lesson-num-cnt-skip5',
    visualKinds: ['number-line'],
  },
  {
    id: 'skill-add-fact-10',
    subject: 'arithmetic',
    strand: 'addition',
    code: 'ADD.FACT.10',
    name: 'Recall addition facts within 10',
    band: 'early',
    prerequisites: ['NUM.CNT.20'],
    lessonRef: 'lesson-add-fact-10',
    visualKinds: ['ten-frame', 'number-line'],
  },
  {
    id: 'skill-add-regroup-2d',
    subject: 'arithmetic',
    strand: 'addition',
    code: 'ADD.REGROUP.2D',
    name: 'Add two-digit numbers with regrouping',
    band: 'middle',
    prerequisites: ['ADD.FACT.10'],
    lessonRef: 'lesson-add-regroup-2d',
    visualKinds: ['place-value-blocks', 'number-line'],
  },
  {
    id: 'skill-frac-equal',
    subject: 'arithmetic',
    strand: 'fractions',
    code: 'FRAC.EQUAL',
    name: 'Recognise a fraction as equal pieces of a whole',
    band: 'early',
    prerequisites: [],
    lessonRef: 'lesson-frac-equal',
    visualKinds: ['fraction-bar', 'array'],
  },
  {
    id: 'skill-frac-compare',
    subject: 'arithmetic',
    strand: 'fractions',
    code: 'FRAC.COMPARE',
    name: 'Compare fractions with the same denominator',
    band: 'middle',
    prerequisites: ['FRAC.EQUAL'],
    lessonRef: 'lesson-frac-compare',
    visualKinds: ['fraction-bar', 'number-line'],
  },
] as const satisfies readonly Skill[];
