import { createRespondStreamer, type AiClient, type RespondStreamer } from '@/ai';
import {
  createContentCacheService,
  createFallbackService,
  createReliableContentService,
  type GeneratedContent,
} from '@/content';
import {
  ARITHMETIC_SKILL_CODES,
  isArithmeticLookup,
  nextItemFor,
  toGeneratedContent,
} from '@/content/generation';
import { outputSafety } from '@/content/output-safety';
import type { InventoryService } from '@/curriculum';
import { ServiceUnavailableError } from '@/errors';
import { createGateObserver } from '@/observability/gate-metrics';
import { scrubLearnerContext } from '@/privacy';
import { createQualityGate, speakableGate, type QualityGate } from '@/quality';
import type { ContentItemRepository } from '@/repositories/content-item.repository';
import { createAheadService } from '@/services/content/ahead.service';
import { contentScope } from '@/services/content/personalise';

import type { Phase1Repositories, Phase1RuntimeDeps } from './runtime.types';

export type ContentServices = Readonly<{
  gate: ReturnType<typeof createQualityGate>;
  reliable: ReturnType<typeof createReliableContentService>;
  ahead: ReturnType<typeof createAheadService>;
  /** P2H-07: present only when the deployment can stream; absent means every move arrives whole. */
  respond?: RespondStreamer;
}>;

export function buildContentServices(
  deps: Phase1RuntimeDeps,
  repositories: Phase1Repositories,
  inventory: InventoryService,
): ContentServices {
  const gate = createQualityGate(
    (text) => outputSafety(text),
    createGateObserver({ metrics: deps.metrics, logger: deps.logger }),
  );
  const fallback = createFallbackService({ inventory, gate });
  const cache = createContentCacheService({
    repository: repositories.content,
    accounting: deps.spend,
  });
  const reliable = createReliableContentService({
    cache,
    fallback,
    gate,
    generate: (input, signal) =>
      generateContent({
        ai: deps.ai,
        inventory,
        bank: repositories.content,
        input,
        ...(signal === undefined ? {} : { signal }),
      }),
    recordFailure: (verdict) => {
      deps.logger.warn(
        { checks: verdict.reasons.map((reason) => reason.code) },
        'Generated content failed the quality gate',
      );
      return Promise.resolve();
    },
  });
  const ahead = createAheadService({
    prepare: async (request: Parameters<typeof reliable.resolve>[0], signal) => {
      if (!signal.aborted) await reliable.resolve(request, signal);
    },
    onError: (error, sessionId) => {
      deps.logger.warn({ err: error, sessionId }, 'Ahead content generation failed');
    },
  });
  return { gate, reliable, ahead, ...respondStreamer(deps, gate) };
}

function respondStreamer(
  deps: Phase1RuntimeDeps,
  gate: QualityGate,
): Readonly<{ respond?: RespondStreamer }> {
  return deps.gatedStreamer === undefined
    ? {}
    : { respond: createRespondStreamer(deps.gatedStreamer(speakableGate(gate))) };
}

type ContentRequest = Parameters<ContentServices['reliable']['resolve']>[0];

/**
 * P2H-10: arithmetic is generated by code and proven by the checker; everything else is
 * prompted.
 *
 * Before this ticket the arithmetic branch threw, and six hand-written fallbacks were the
 * whole bank. The split stays, because it is the right one: an item whose answer can be proven
 * should never be phrased by a model that might change a number, and a rhyme cannot be
 * enumerated.
 */
async function generateContent(
  request: Readonly<{
    ai: AiClient;
    inventory: InventoryService;
    bank: ContentItemRepository;
    input: ContentRequest;
    signal?: AbortSignal;
  }>,
): Promise<GeneratedContent> {
  const { ai, inventory, bank, input, signal } = request;
  const skill = inventory.getSkill(input.skillCode);
  if (skill === null) throw new ServiceUnavailableError('use verified fallback');
  if (skill.subject === 'arithmetic') return generateArithmetic(bank, input);
  return generatePrompted({ ai, skill, input, ...(signal === undefined ? {} : { signal }) });
}

/**
 * The next item of this skill the bank does not already hold.
 *
 * Reading the bank first is what stops a cache miss becoming a duplicate row: the cache
 * excludes the items this child has just seen, so without this the generator would rebuild
 * one of them and store it a second time. When every point in the space is already stored
 * there is no new item, and the caller falls back to what is cached.
 */
async function generateArithmetic(
  bank: ContentItemRepository,
  input: ContentRequest,
): Promise<GeneratedContent> {
  if (!isArithmeticLookup(input, ARITHMETIC_SKILL_CODES)) {
    throw new ServiceUnavailableError('use verified arithmetic fallback');
  }
  const stored = new Set(
    await bank.listContentHashes({
      skillCode: input.skillCode,
      band: input.band,
      kind: input.kind,
    }),
  );
  const item = nextItemFor(input, stored);
  if (item === null) throw new ServiceUnavailableError('arithmetic parameter space exhausted');
  return toGeneratedContent(item, input.kind);
}

async function generatePrompted(
  request: Readonly<{
    ai: AiClient;
    skill: Readonly<{ code: string; name: string }>;
    input: ContentRequest;
    signal?: AbortSignal;
  }>,
): Promise<GeneratedContent> {
  const { ai, skill, input, signal } = request;
  const context = scrubLearnerContext(
    { identifiers: {}, gradeBand: input.band, skill: skill.code },
    { pseudonym: 'omit' },
  );
  const result = await ai.run(
    'practice-item',
    { context, skill: skill.name, difficulty: 'same' },
    { studentId: input.studentId, ...(signal === undefined ? {} : { signal }) },
  );
  const body = {
    prompt: result.data.prompt,
    answerKey: result.data.answer,
    ...(result.data.options === undefined
      ? {}
      : { choices: result.data.options.map((option) => option.text) }),
  };
  return {
    gateInput: {
      id: `generated-${skill.code}`,
      kind: 'text',
      band: input.band,
      childText: result.data.prompt,
      factual: false,
      grounding: 'unsupported',
    },
    draft: {
      kind: input.kind,
      skillCode: skill.code,
      band: input.band,
      body,
      sourceModel: result.metadata.model,
      promptName: result.metadata.promptName,
      promptVersion: result.metadata.promptVersion,
      scope: contentScope({ studentId: input.studentId, usesLearnerMemory: false }),
    },
  };
}
