import { allRules, BURN_RATE_WINDOWS, type AlertRule } from '@/observability/slo/burn-rate';
import { sloCoverage, SLOS, type Slo } from '@/observability/slo/slos';

/**
 * Renders the alert rules as a Prometheus rule file (X-04).
 *
 * Written by hand rather than with a YAML library for one reason: the output is a generated
 * artefact that a human reads in a diff, so its shape — the comment header, the order, the
 * spacing — is part of what it is for. A serialiser would produce valid YAML that churns.
 */
export const RULES_HEADER = [
  '# Generated by `npm run slo:rules -w @aria/api`. Do not edit by hand.',
  '#',
  '# One group per severity, generated from apps/api/src/observability/slo/slos.ts, which is',
  '# generated from nothing: it is the hand-written list of the bars in master-plan.md §11.',
  '# Change a number there and regenerate; a threshold edited here is a threshold that',
  '# disagrees with the plan and with /status.',
];

export function renderRuleFile(slos: readonly Slo[] = SLOS): string {
  const rules = allRules(slos);
  const lines = [
    ...RULES_HEADER,
    ...coverageComment(slos),
    '',
    'groups:',
    ...severities().flatMap((severity) => group(severity, rules)),
  ];
  return `${lines.join('\n')}\n`;
}

/**
 * The uninstrumented bars, named in the generated file.
 *
 * Somebody reading the alert rules to find out what is watched should be told, in the same
 * file, what is not. A gap that only exists in a TypeScript constant is a gap nobody in an
 * incident will find.
 */
function coverageComment(slos: readonly Slo[]): readonly string[] {
  const coverage = sloCoverage(slos);
  if (coverage.gaps.length === 0) return [];
  return [
    '#',
    `# ${String(coverage.instrumented)} of ${String(coverage.total)} bars are watched here.`,
    '# Not watched, and why:',
    ...coverage.gaps.map((gap) => `#   - ${gap.id}: ${firstSentence(gap.blockedBy)}`),
  ];
}

function severities(): readonly AlertRule['labels']['severity'][] {
  return [...new Set(BURN_RATE_WINDOWS.map((window) => window.severity))];
}

function group(
  severity: AlertRule['labels']['severity'],
  rules: readonly AlertRule[],
): readonly string[] {
  const selected = rules.filter((rule) => rule.labels.severity === severity);
  if (selected.length === 0) return [];
  return [
    `  - name: aria-slo-${severity}`,
    '    rules:',
    ...selected.flatMap((rule) => ruleLines(rule)),
  ];
}

function ruleLines(rule: AlertRule): readonly string[] {
  return [
    `      - alert: ${rule.alert}`,
    `        expr: ${quote(rule.expr)}`,
    `        for: ${rule.for}`,
    '        labels:',
    `          severity: ${rule.labels.severity}`,
    `          slo: ${rule.labels.slo}`,
    '        annotations:',
    `          summary: ${quote(rule.annotations.summary)}`,
    `          bar: ${quote(rule.annotations.bar)}`,
    `          runbook: ${quote(rule.annotations.runbook)}`,
  ];
}

/** Single-quoted, which in YAML escapes everything except the single quote itself. */
function quote(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

function firstSentence(text: string): string {
  const stop = text.indexOf('. ');
  return stop === -1 ? text : text.slice(0, stop + 1);
}
