-- 001 — identity
--
-- The smallest schema the rest of Phase 0 and Phase 1 can reference: a parent, and the
-- students that belong to them. Nothing about credentials is decided here; P0-26 chooses who
-- issues them, and whatever it chooses attaches to these rows rather than replacing them.
--
-- Conventions established here and followed by every later migration:
--   * TIMESTAMPTZ always, defaulted to now(). Never TIMESTAMP — a naive timestamp is a bug
--     waiting for the first user in another time zone.
--   * UUID primary keys, generated by the application through the `ids` port, so a test can
--     make them deterministic.
--   * Every foreign key states its ON DELETE behaviour explicitly.
--   * Forward-only. Once merged this file is never edited; the runner verifies its checksum.

-- Case-insensitive text, so 'Parent@Example.com' and 'parent@example.com' cannot both exist.
-- Doing this in the column type rather than by lower()-ing in application code means every
-- future query gets it right without having to remember to.
CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE parent (
    id           UUID        PRIMARY KEY,
    -- Nullable on purpose: P0-26 has not decided whether an account is identified by email,
    -- by a provider subject, or by something else. A row can exist before an address does.
    email        CITEXT,
    display_name TEXT        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT parent_display_name_present CHECK (length(btrim(display_name)) > 0)
);

-- A partial unique index rather than a UNIQUE constraint. NULLs are distinct in Postgres so a
-- plain UNIQUE would happen to work, but stating the predicate makes the intent explicit and
-- is the pattern later tables reuse for nullable natural keys.
CREATE UNIQUE INDEX parent_email_key ON parent (email) WHERE email IS NOT NULL;

CREATE TABLE student (
    id           UUID        PRIMARY KEY,
    -- ON DELETE CASCADE is the schema honouring master-plan.md §12.9, "delete means delete".
    -- A parent erasing their account must take the child's history with it as a property of
    -- the database, not as a cleanup script somebody has to remember to run.
    parent_id    UUID        NOT NULL REFERENCES parent (id) ON DELETE CASCADE,
    display_name TEXT        NOT NULL,
    -- Grade is the stored fact; band is derived from it by `bandForGrade` in @aria/shared and
    -- persisted alongside so a query can filter by band without a join or a CASE. The two are
    -- kept consistent by the repository, which derives band rather than accepting one.
    grade        TEXT        NOT NULL,
    band         TEXT        NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- The vocabulary is duplicated here on purpose. The database is the last line of defence
    -- and has to defend itself against any writer, including a future service that forgets.
    -- A unit test asserts these lists still match GRADES and BANDS in @aria/shared.
    CONSTRAINT student_grade_valid CHECK (
        grade IN ('TK', 'K', '1', '2', '3', '4', '5', '6', '7', '8')
    ),
    CONSTRAINT student_band_valid CHECK (band IN ('early', 'middle', 'senior')),
    CONSTRAINT student_display_name_present CHECK (length(btrim(display_name)) > 0)
);

-- Every student lookup in the product starts from the parent, so this index is not optional.
CREATE INDEX student_parent_id_idx ON student (parent_id);

-- Two children in one family cannot share a name, case-insensitively: the parent has to be
-- able to tell them apart in the picker, and the child has to recognise their own row.
CREATE UNIQUE INDEX student_parent_display_name_key ON student (parent_id, lower(display_name));
