package com.mathtutor.practice;

import com.mathtutor.ai.GenerationContext;
import com.mathtutor.ai.GenerationService;
import com.mathtutor.ai.content.GeneratedQuestion;
import com.mathtutor.ai.content.Hint;
import com.mathtutor.ai.content.PracticeBatch;
import com.mathtutor.auth.security.AuthPrincipal;
import com.mathtutor.common.AiException;
import com.mathtutor.common.NotFoundException;
import com.mathtutor.curriculum.CurriculumService;
import com.mathtutor.curriculum.CurriculumService.TopicContext;
import com.mathtutor.practice.dto.GuidedDtos.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.UUID;

/**
 * Guided practice: Aria teaches while the child solves. A wrong answer returns a
 * short hint (generated by the fast model) instead of the solution, so the child
 * keeps trying. The solution is only revealed when they get it right or ask for it.
 */
@Service
public class GuidedPracticeService {

    private final QuestionBankRepository questionRepository;
    private final CurriculumService curriculumService;
    private final GenerationService generationService;
    private final QuestionStore questionStore;
    private final com.mathtutor.progress.ProgressService progressService;

    public GuidedPracticeService(QuestionBankRepository questionRepository,
                                 CurriculumService curriculumService,
                                 GenerationService generationService,
                                 QuestionStore questionStore,
                                 com.mathtutor.progress.ProgressService progressService) {
        this.questionRepository = questionRepository;
        this.curriculumService = curriculumService;
        this.generationService = generationService;
        this.questionStore = questionStore;
        this.progressService = progressService;
    }

    @Transactional
    public GuidedQuestionDto start(AuthPrincipal student, UUID topicId) {
        progressService.assertUnlocked(student.id(), topicId);
        TopicContext ctx = curriculumService.resolveTopicContext(topicId);
        GenerationContext genCtx = new GenerationContext(
                ctx.subjectName(), ctx.gradeName(), ctx.topicName(), ctx.objectives());

        PracticeBatch batch = generationService.generatePractice(genCtx, "MEDIUM", 1, student.id());
        if (batch.questions() == null || batch.questions().isEmpty()) {
            throw new AiException("Aria could not create a guided question. Please try again.");
        }
        GeneratedQuestion gq = batch.questions().get(0);
        QuestionBank saved = questionStore.persist(topicId, gq, "MEDIUM", "GUIDED");
        return new GuidedQuestionDto(saved.getId(), saved.getType(),
                saved.getPromptText(), questionStore.readChoices(saved.getChoices()));
    }

    @Transactional
    public GuidedFeedback attempt(AuthPrincipal student, GuidedAttemptRequest req) {
        QuestionBank q = questionRepository.findById(req.questionId())
                .orElseThrow(() -> new NotFoundException("Question not found"));

        if (AnswerMatcher.matches(req.response(), q.getCorrectAnswer())) {
            return new GuidedFeedback(true, null, q.getSolution(), q.getCorrectAnswer());
        }

        TopicContext ctx = curriculumService.resolveTopicContext(q.getTopicId());
        Hint hint = generationService.generateHint(
                ctx.subjectName(), q.getPromptText(), req.response(), req.attempt(), student.id());
        return new GuidedFeedback(false, hint.hint(), null, null);
    }

    @Transactional(readOnly = true)
    public GuidedFeedback reveal(UUID questionId) {
        QuestionBank q = questionRepository.findById(questionId)
                .orElseThrow(() -> new NotFoundException("Question not found"));
        return new GuidedFeedback(false, null, q.getSolution(), q.getCorrectAnswer());
    }
}
